name: petstore
description: Dart gRPC sample client and server.
publish_to: none

environment:
  sdk: '>=2.12.0'

dependencies:
  async: ^2.2.0
  protobuf: 
  grpc_googleapis: ^2.0.22

dev_dependencies:
  lints: ^2.0.0